[[headers]]
  for = "/*"
  [headers.values]
    # РАЗРЕШАЕМ iframe ТОЛЬКО для OK.ru
    X-Frame-Options = "ALLOW-FROM https://ok.ru"
    
    # CSP для OK.ru - МЕНЬШЕ ОГРАНИЧЕНИЙ на время разработки
    Content-Security-Policy = "
      default-src * 'unsafe-inline' 'unsafe-eval' data: blob:;
      script-src * 'unsafe-inline' 'unsafe-eval' blob:;
      connect-src *;
      style-src * 'unsafe-inline';
      img-src * data: blob:;
      frame-src *;
      frame-ancestors https://ok.ru https://*.ok.ru;
    "
    
    # Дополнительные заголовки для CORS
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "*"
